name: Super-Linter

on:
  push:
  pull_request:
    branches: [master]

jobs:
  super-lint:
    name: Lint Code Base
    # I don't think running lint on multiple os' will do any good.
    runs-on: ubuntu-latest

    # Don't run action if commit message has #noaction in it.
    if: "! contains(github.event.head_commit.message, '#noaction')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
